# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause this
# file to always be loaded, without a need to explicitly require it in any files.
#
ENV["RAILS_ENV"] ||= 'default'
require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
require 'rspec/autorun'
require 'database_cleaner'
require "rack_session_access/capybara"
# Requires supporting ruby files with custom matchers and macros, etc,
# in spec/support/ and its subdirectories.
Dir[Rails.root.join("spec/support/**/*.rb")].each {|f| require f}

# OmniAuth.config.test_mode = true

# OmniAuth.config.mock_auth[:fitbit] = OmniAuth::AuthHash.new({
#   provider: 'fitbit',
#   uid: '12345',
#   full_name: 'Michael Pourhadi',
#   credentials: {
#       token: '2f490eb8444c48c1a3e5a3aa738c5018',
#       secret: '01c8682329934edba0f407d27d0494d8'
#   }
# })


RSpec.configure do |config|
  config.include Capybara::DSL

  config.mock_with :rspec

  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each, :js => true) do
    DatabaseCleaner.strategy = :truncation
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end
end